---
version: "2.1"
services:
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2:latest
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - config:/config
      - downloads:/downloads
    ports:
      - 10004:5076
    restart: unless-stopped
    
volumes:
  config:
  downloads:
