version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'Europe/Berlin'
    #networks:
     # - default
    ports:
      #- "137:137/udp"
      #- "138:138/udp"
      #- "139:139/tcp"
      - "445:445/tcp"
    #read_only: true
    #tmpfs:
    #  - /tmp
    restart: unless-stopped
    #stdin_open: true
    #tty: true
    volumes:
      - /home/mark/samba/1:/mnt00:z
      - /home/mark/samba/2:/mnt01:z
      #- /mnt:/mnt:z
      #- /mnt2:/mnt2:z
    command: '-s "Mount;/mnt00" -s "Marks Volume;/mnt00;yes;no;no;mark" -u "mark;caioe" -p'

#networks:
#  default:
