version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: samba   
    environment:
      TZ: 'Europe/Berlin'
      WORKGROUP: 'WORKGROUP'
      USERID: '1000'
      GROUPID: '1000'
GROUPID
    ports:
      - "445:445/tcp"
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /home/mark/samba:/mnt:z    
    command: '-s "Mount;/mnt0 -s "Volume 1;/mnt/1;yes;no;no;mark" -s "Volume 2;/mnt/2;yes;no;no;mark" -s "Volume 3;/mnt/3;yes;no;no;mark,jasmin" -u "mark;pass" -u "jasmin;pass" -p'
