version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: 'Europe/Berlin'
    ports:
      - "445:445/tcp"
    restart: unless-stopped
    volumes:
      - /home/mark/samba/1:/mnt00:z
      - /home/mark/samba/2:/mnt01:z
      - /home/mark/samba/3:/mnt02:z
    command: '-u "mark;caioe" -u "jasmin;caioe" -s "Marks Volume;/mnt00;yes;no;no;mark" -s "JAzzs Volume;/mnt01;yes;no;no;jasmin -s "Public;/mnt02;yes;no;no;mark,jasmin -p'
